Fix windows build
/permissive- flag is now required to build with streflop on windows.
Stops "error C2668: 'fpclassify': ambiguous call to overloaded function"
fixes #294